- npm-shrinkwrap.json
- package.json
- src/lib/base-command.ts
- src/lib/errors.ts
closes GGT-2065
This makes our errors send events to Sentry
> Add sentry

- .envrc
- .gitignore
- cspell.json
- flake.lock
- flake.nix
So you can just cd in and get started!
> Add nix flake for dev env

- .changeset/twelve-clouds-unite.md
- spec/utils/__snapshots__/errors.spec.ts.snap
- src/utils/base-command.ts
- src/utils/errors.ts
This will show us the rendered message in the Sentry event.
> Render the message before capturing the exception

- .changeset/afraid-kangaroos-kiss.md
- spec/commands/list.spec.ts
- spec/commands/sync.spec.ts
- spec/utils/flags.spec.ts
- src/commands/list.ts
- src/commands/sync.ts
- src/utils/context.ts
- src/utils/flags.ts
Adds a `ggt list` command for listing out the apps that a user has access to.
Depends on https://github.com/gadget-inc/gadget/pull/5906
> Add a command for listing out the current apps you have access to

- .cspell/project-words.txt
- .envrc
- .prettierignore
- CONTRIBUTING.md
- flake.nix
- spec/commands/sync.spec.ts
- src/commands/help.ts
- src/commands/sync.ts
- src/utils/base-command.ts
- src/utils/client.ts
- src/utils/context.ts
- src/utils/fs-utils.ts
- src/utils/promise.ts
Renames some stuff, adds a bunch of doc comments, and updates our contributing guide. Trying to get all the knowledge from my brain into the codebase so it's easier for others to work on.
> Documentation

- npm-shrinkwrap.json
- package.json
> Revert "Bump graphql-ws from 5.13.1 to 5.14.0"

- npm-shrinkwrap.json
- package.json
> Revert "Bump @sentry/node from 7.55.2 to 7.56.0"

- .cspell/project-words.txt
- npm-shrinkwrap.json
- package.json
- spec/commands/list.spec.ts
- spec/commands/login.spec.ts
- spec/commands/sync.spec.ts
- spec/commands/whoami.spec.ts
- spec/services/app.spec.ts
- spec/services/errors.spec.ts
- spec/services/filesync.spec.ts
- spec/services/user.spec.ts
- src/commands/list.ts
- src/commands/login.ts
- src/commands/sync.ts
- src/commands/whoami.ts
- src/services/app.ts
- src/services/errors.ts
- src/services/filesync.ts
- src/services/fs-utils.ts
- src/services/session.ts
- src/services/user.ts
This extracts filesync related logic that will be used for the upcoming push/pull commands.
> Extract filesync logic

- src/commands/sync.ts
- src/services/filesync.ts
> Extract more filesync logic

- .changeset/moody-parrots-wink.md
- spec/commands/sync.spec.ts
- src/commands/sync.ts
I tried fixing this in #460, but missed an edge case. This fixes that.
> Fix paths added to recentRemoteChanges

- CHANGELOG.md
- spec/commands/root.spec.ts
- spec/services/command/__snapshots__/command.spec.ts.snap
- src/commands/root.ts
- src/services/command/command.ts
We want to make some more changes to `ggt deploy` before it's ready for the public.
> Disable ggt deploy

- .envrc
- spec/commands/__snapshots__/root.spec.ts.snap
- src/__generated__/edit.graphql
- src/__generated__/graphql.ts
- src/commands/deploy.ts
- src/services/app/edit-graphql.ts
- src/services/command/command.ts
- Restore ability to run deploy command behind an undocumented env var (not quite a revert of 4d915b586afa5aeb5f37defba19b31c6ef977157)
- Show problematic apiIdentifiers before names if they exist
Depends on https://github.com/gadget-inc/gadget/pull/9423
> Show sourcefile problems on deploy

- .changeset/fix-files-version-mismatch.md
- spec/services/filesync/filesync.spec.ts
- src/services/filesync/filesync.ts
fixes #435 #869 
closes GGT-5374
> Fix "Files version mismatch"

- .changeset/heavy-moose-boil.md
This was actually added in #1117 here: https://github.com/gadget-inc/ggt/pull/1117/files#diff-915f9738f6857cf53c7af2b548058be3cf85fef8a7b28e67393128fd9d3ad4bcR47-R53
I just forgot to add the changeset 🤦
> Automatically retry GraphQL query errors

- .changeset/improve-usage.md
- .cspell/project-words.txt
- npm-shrinkwrap.json
- package.json
- scripts/generate-readme.ts
- spec/__support__/filesync.ts
- spec/commands/__snapshots__/root.spec.ts.snap
- spec/commands/deploy.spec.ts
- spec/commands/root.spec.ts
- spec/services/command/command.spec.ts
- src/commands/deploy.ts
- src/commands/list.ts
- src/commands/login.ts
- src/commands/logout.ts
- src/commands/root.ts
- src/commands/sync.ts
- src/commands/version.ts
- src/commands/whoami.ts
- src/services/command/command.ts
I was playing with the deploy command this weekend and found myself wanting to change its output a bit. All of these changes are personal preference, so if you don't like them let me know and I'll revert!
<details>
<summary>Before</summary>
https://github.com/gadget-inc/ggt/assets/21965521/c5e264a1-8ab2-4b44-8bee-e6401c59c2fd
```
App: sure
Local files have diverged from remote. Run a sync once to converge your files or keep ggt sync running in the background.
✔ How would you like to proceed? › Sync once
→ Sent 01:45:25 PM
routes/GET-hello.js  updated ± 
Issues detected
• routes/GET-hello.js 1 issue
✖ Typescript Unexpected keyword or identifier: file line 12
• routes/GET-test.ts 2 issues
✖ Typescript Identifier expected: file line 10
✖ Typescript Expression expected: file line 15
• …
```
> Deploy Changes

- src/commands/deploy.ts
- src/commands/sync.ts
- src/services/app/edit/edit.ts
- src/services/filesync/filesync.ts
This will be used to simplify the deploy command.
> Add ability to resubscribe to a subscription

- spec/__support__/edit.ts
- spec/services/filesync/sync-json.spec.ts
- spec/services/output/report.spec.ts
- src/services/app/edit/client.ts
- src/services/filesync/sync-json.ts
This PR in conjunction with https://github.com/gadget-inc/gadget/pull/10083
Should fix ggt ever touching production again and mucking things.
> Fixed ggt synching to production when it's a fresh start

- spec/__support__/mock.ts
- spec/commands/__snapshots__/root.spec.ts.snap
- spec/commands/deploy.spec.ts
- src/__generated__/edit.graphql
- src/__generated__/graphql.ts
- src/commands/deploy.ts
- src/services/app/edit/operation.ts
- src/services/output/spinner.ts
This PR is the ggt side of https://linear.app/gadget-dev/issue/GGT-5970
The gadget side is here: https://github.com/gadget-inc/gadget/pull/10259
> prompt user for confimation if deploy will cost them money

- npm-shrinkwrap.json
- package.json
- spec/__support__/mock.ts
- spec/commands/deploy.spec.ts
- spec/services/filesync/changes.spec.ts
- src/commands/dev.ts
- src/services/filesync/changes.ts
- src/services/filesync/filesync.ts
- src/services/output/log/format/pretty.ts
- src/services/output/select.ts
- src/services/output/spinner.ts
Noticed some weird spacing on Windows beside our spinner's checkmark. Using [figures](https://github.com/sindresorhus/figures) should fix this.
> Use figures

- .eslintrc.json
- npm-shrinkwrap.json
- package.json
- spec/__support__/mock.ts
- src/commands/dev.ts
- src/services/config/config.ts
- src/services/filesync/changes.ts
- src/services/filesync/filesync.ts
- src/services/output/log/format/pretty.ts
- src/services/output/select.ts
- src/services/output/spinner.ts
- src/services/output/symbols.ts
I tried to fix this in #1297, but that didn't end up working. Doing it this way does.
> Fix symbol spacing on Windows

- spec/services/filesync/__snapshots__/error.spec.ts.snap
- spec/services/filesync/error.spec.ts
- spec/services/filesync/filesync.spec.ts
- src/commands/pull.ts
- src/commands/push.ts
- src/services/filesync/error.ts
- src/services/filesync/sync-json.ts
> Allow push and pull to use --allow-unknown-directory

- .changeset/cleanup-empty-directories.md
- spec/services/filesync/filesync.spec.ts
- src/services/filesync/filesync.ts
Thanks to @MillanWangGadget, I think I finally figured this out!
> Cleanup empty directories

- .changeset/fix-404s.md
- src/services/app/client.ts
> Don't hardcode `--development` suffix

- .changeset/downgrade-execa.md
- .github/dependabot.yml
- npm-shrinkwrap.json
- package.json
> Downgrade execa

- .changeset/grouped-app-list.md
- spec/__support__/app.ts
- spec/commands/list.spec.ts
- spec/services/filesync/sync-json.spec.ts
- src/commands/list.ts
- src/services/app/app.ts
- src/services/filesync/sync-json.ts
- src/services/output/select.ts
- src/services/util/types.ts
Updates our app selector to group apps by their team.
Since I figured this is probably gonna be a useful thing to do in the future, I updated `select` to handle grouped choices.
> implement grouped app list

- .changeset/disable-automatic-source-maps.md
- src/main.ts
https://discord.com/channels/836317518595096598/1336676719855145000
> Don't automatically enable source maps

- .changeset/smooth-rice-rhyme.md
- README.md
- spec/commands/__snapshots__/root.spec.ts.snap
- spec/commands/add.spec.ts
- src/__generated__/graphql.ts
- src/commands/add.ts
- src/services/app/edit/operation.ts
New `add env` command has been added to create a new environment
> New `add env` command

- .github/pull_request_template.md
... a description that explains what, why, and how ...
If this PR will affect change user-facing behavior, add detailed information about the change here to prompt an AI generated changelog entry.
If no changelog is required, write `no-changelog-required` in square brackets `[]`.
> changing the description back to what it was
