src/commands/sync.ts

`npx` sends 2 SIGINT signals when pressing Ctrl+C which causes `ggt sync` to always force exit  😞 
This PR handles that.

Handle multiple SIGINTs via npx

---

spec/commands/sync.spec.ts
src/commands/sync.ts
src/lib/base-command.ts
src/lib/errors.ts
src/lib/fs-utils.ts

This makes `ggt sync` throw an error if it can't load the `.ggt/sync.json` file in a non-empty directory. This should make it harder for users to accidentally run `ggt sync` in the wrong directory.
Before, we used to log a warning and stop if we walked too many files. This removes the need for that.
I still struggle to write clear error messages/docs so feel free to suggest changes 😄

Make `.ggt/sync.json` required and add --force flag

---

.cspell/project-words.txt
README.md
spec/commands/sync.spec.ts
src/commands/sync.ts
src/lib/errors.ts
src/lib/fs-utils.ts

closes GGT-1927
This makes `ggt sync` save and remember the last `--app` it was given.
Now, if you don't provide the `--app` flag, `ggt sync` will only prompt you to select one if the directory doesn't exist or is empty. If you do provide the `--app` flag, but it doesn't match the one stored in `.ggt/sync.json`, it will exit with an error.
Example of passing a different `--app` than the one used last time:
```sh-session
$ ggt sync --app scott tmp/apps/scott
Ready
Received
← .gadget/client/dist-cjs/Client.d.ts
← .gadget/client/dist-cjs/Client.js
← .gadget/client/dist-cjs/Client.js.map
← .gadget/client/dist-cjs/iife-export.d.ts
← .gadget/client/dist-cjs/iife-export.js
← .gadget/client/dist-cjs/iife-export.js.map
← .gadget/client/dist-cjs/index.d.ts
← .gadget/client/dist-cjs/index.js
← …
```

Save and validate `--app`

---

README.md
spec/commands/sync.spec.ts
src/commands/sync.ts
src/lib/errors.ts

This moves `.ggt/sync.json` -> `.gadget/sync.json`. I don't think we need 2 separate Gadget maintained directories. I also flattened `lastWritten` since it's unnecessary and doesn't actually align with how `mtime` works.
This is technically a breaking change, so attempting to sync with an existing local dir will throw errors complaining that it can't find the `.gadget/sync.json` file. I didn't write a migration step because only the staff have been using `ggt` and we're currently in alpha.
If someone wants to migrate an existing local directory themselves, they can move `.ggt/sync.json` -> `.gadget/sync.json` and flatten `lastWritten`:
```diff
{
"app": "scott",
-   "lastWritten": {
"filesVersion": "326",
"mtime": 1661528864319
-   }
}
```

Move `sync.json` to `.gadget`

---

src/commands/sync.ts

This changes the `ignored` option when instantiating `chokidar` to use our `Ignorer`.
---
I noticed the following being logged with the `--debug` flag while I was investigating #18
```
ggt:sync skipping event caused by added directory node_modules +174ms
ggt:sync skipping event caused by added directory node_modules/@fastify +27ms
ggt:sync skipping event caused by added directory node_modules/@gadget-client +0ms
ggt:sync skipping event caused by added directory node_modules/@gadgetinc +0ms
ggt:sync skipping event caused by added directory node_modules/@graphql-typed-document-node +1ms
ggt:sync skipping event caused by added directory node_modules/@opentelemetry +0ms
ggt:sync skipping event caused by added directory node_modules/@sindresorhus +0ms
ggt:sync skipping event caused by added …
```

Use `Ignorer` for `chokidar`'s `ignored` option

---

.changeset/clever-pots-remember.md
src/commands/sync.ts
src/utils/client.ts

Fixes one of the scenarios that causes the `Files version mismatch` exception to occur.

Only update files version if it's greater than current

---

.changeset/shiny-days-join.md
spec/commands/sync.spec.ts
src/commands/sync.ts

`unlinkDir` events are redundant because all the files in the deleted directory also emit `unlink` events.

Ignore `unlinkDir` events

---

spec/jest.setup.ts
spec/utils/base-command.spec.ts
spec/utils/context.spec.ts
src/utils/base-command.ts
src/utils/client.ts
src/utils/context.ts

Points our development gadget domains to the new urls without the ports and adds the ability to overwrite the gadget domains with environment variables.

Add Gadget specific domains to context

---

.changeset/pink-clocks-flow.md
src/commands/sync.ts

Fixes #209 and #298
Previously, we were using the sleepUntil utility to await the end state of the sync before quitting. sleepUntil loops internally with a sleep(0), which uses a lot of CPU! This updates us to use a promise that we manually resolve instead, which means the node process can actually sleep while nothing is happening. 
CPU profile before:
CPU profile after:

Await finishing using a promise instead of polling state

---

.changeset/nine-apes-swim.md
package.json
spec/utils/base-command.spec.ts
src/utils/base-command.ts

When we call `this.exit(0)` [here](https://github.com/gadget-inc/ggt/blob/sc/handle-exit-0/src/utils/base-command.ts#L87), it throws the following error:
```
GGT_CLI_UNEXPECTED_ERROR: An unexpected error occurred
Error: EEXIT: 0
at Object.exit (/Users/scott/Code/gadget/ggt/node_modules/@oclif/core/lib/errors/index.js:21:11)
at Sync.exit (/Users/scott/Code/gadget/ggt/node_modules/@oclif/core/lib/command.js:122:23)
at Sync.init (/Users/scott/Code/gadget/ggt/lib/utils/base-command.js:70:29)
at async Sync.init (/Users/scott/Code/gadget/ggt/lib/commands/sync.js:143:9)
at async Sync._run (/Users/scott/Code/gadget/ggt/node_modules/@oclif/core/lib/command.js:107:13)
at async Config.runCommand (/Users/scott/Code/gadget/ggt/node_modules/@oclif/core/lib/config/config.js:328:25)
at async Object.run …
```

Ignore `this.exit(0)` errors

---

.changeset/happy-queens-crash.md
src/utils/base-command.ts

When someone runs `ggt sync --app foo`, we make sure they actually have an app named `foo` by making a request to Gadget. If you have an app named `foo` and you're logged in, all good 👍 
However, if you're not logged in, we consider you to have no apps which means that `ggt sync` will always respond with the following error:
```
GGT_CLI_FLAG_ERROR: Invalid value provided for the -a, --app flag
Unknown application:
foo
It doesn't look like you have any applications.
Visit https://gadget.new to create one!
```
Sync automatically logs you in if you're not already, but before this PR we logged you in **after** parsing flags 🤦 
This PR makes us log you in before parsing flags so we can actually check which apps you have.

Fix auto login

---

.changeset/sweet-radios-listen.md
flake.nix
package.json
spec/commands/sync.spec.ts
spec/util.ts
src/commands/sync.ts
src/utils/fs-utils.ts

This PR adds support for syncing empty directories to Gadget and vice versa. Many of the changes are related to detecting directories and ensuring that their paths always end with a trailing slash. Syncing the directories to Gadget seem to work fine with the local fs mode, but when syncing from Gadget we set the mode to `0o755` which is what we currently do for directories that contain files

Allow empty folders to be synced to gadget and vice versa

---

.changeset/thick-students-cry.md
src/commands/sync.ts
src/utils/fs-utils.ts

When we syncing for the first time, we create an empty directory if one doesn't already exist. This empty directory shouldn't be included in the list of "changed files" when booting up.

Don't include root directory in `getChangedFiles`

---

.changeset/chilly-steaks-smash.md
src/commands/sync.ts

`fs.readFile` doesn't work when the given path is a directory and rejects with:
```
EISDIR: illegal operation on a directory, read
```
We check to make sure the path isn't a directory when a file changes, but forgot to check when booting up 🤦 -- this fixes that.
Fixes: #409

Don't use `fs.readFile` on directories

---

.changeset/odd-hornets-lick.md
spec/commands/list.spec.ts
spec/commands/sync.spec.ts
spec/utils/base-command.spec.ts
src/commands/list.ts
src/utils/base-command.ts

This improves our `ggt list` command by
- Prompting the user to log in if they aren't already (similar to `ggt sync`)
- Linking them to `https://gadget.new` if they don't have any applications

Improve the list command

---

.changeset/tiny-ants-rule.md
src/commands/sync.ts

Fixes the following issue:
```
Received 3:28:11 PM
← routes/GET.js (changed)
← util/files.js (changed)
3 files in total. 3 changed, 0 deleted.
Sent 3:28:12 PM
→ routes/ (changed)
→ util/ (changed)
2 files in total. 2 changed, 0 deleted.
```

Don't send parent directories back to Gadget

---

.changeset/pink-crabs-bake.md
.github/workflows/cd.yml
npm-shrinkwrap.json
package.json

We got access to the [`ggt`](https://www.npmjs.com/package/ggt) npm package! 🎉 
This changes our package.json's name to `ggt` so we can start using it. We're still going to publish new versions to `@gadgetinc/ggt` while we come up with a strategy to move people over.

Use `ggt` instead of `@gadgetinc/ggt`

---

npm-shrinkwrap.json
spec/commands/sync.spec.ts
src/commands/sync.ts

When we receive an `unlink` or `unlinkDir` event and call `fileStats` on the file, it causes ggt to crash. This makes our `fileStats` function handle deleted files.

Make fileStats handle deleted files/folders

---

.changeset/gold-countries-reflect.md
.gitignore
npm-shrinkwrap.json
package.json
spec/commands/sync.spec.ts
spec/util.ts
src/__generated__/edit.graphql
src/__generated__/graphql.ts
src/commands/sync.ts
src/utils/fs-utils.ts
vitest.config.js

DO NOT MERGE UNTIL https://github.com/gadget-inc/gadget/pull/6955 has been released
This PR switches the fs watcher from `chokidar` to `watcher` which supports rename events. Some necessary changes:
- `watcher` doesn't support symlinks but we're skipping over those anyways
- `watcher` doesn't provider `stats` with events so we need to get those ourselves
- `watcher` doesn't have the same `awaitWriteFinish` option as `chokidar`. Not sure if we ran into any situations or issues where that was required.
- `watcher` doesn't support globs but I don't think that was really necessary as watching the entire dir works just fine
In conjunction with https://github.com/gadget-inc/gadget/pull/6955 will allow us to propagate renamed files to source file references elsewhere in Gadget

Switch to using `watcher` instead of `chokidar` to support renames

---

spec/commands/sync.spec.ts
src/commands/sync.ts

This is an attempt to fix the following flake that keeps popping up on `ubuntu-latest`
```
> ggt@0.2.1 test
> cross-env NODE_OPTIONS="--no-warnings --loader ./node_modules/ts-node/esm.mjs" vitest
RUN  v0.33.0 /home/runner/work/ggt/ggt
❯ spec/commands/sync.spec.ts  (52 tests | 1 failed | 1 skipped) 97298ms
❯ spec/commands/sync.spec.ts > Sync > run > publishing > with an ignore file > reloads the ignore file when it changes
→ Hook timed out in [6](https://github.com/gadget-inc/ggt/actions/runs/5512326345/jobs/10049019813?pr=614#step:5:7)0000ms.
If this is a long-running hook, pass a timeout value as the last argument or configure it globally with "hookTimeout".
✓ spec/services/base-command.spec.ts  (18 tests) 129ms
✓ spec/services/context.spec.ts  (18 tests) 161ms
✓ …
```

Use `file-watch-debounce` for sleep duration

---

.changeset/neat-chicken-think.md
src/commands/sync.ts

The `.DS_Store` file holds metadata on the OSX operating system about the directory it sits in. It provides no functional value by being synced with Gadget.
As such this change removes syncing `.DS_Store` to respect the file-structure on _Gadget_ as well as it make everything a little more tidier 😄

change(ignorePaths): .DS_Store is ignored from syncing with Gadget

---

spec/__support__/filesync.ts
spec/commands/sync.spec.ts

When `expectLocalDir` or `expectGadgetDir` fails a snapshot, I always wonder what the other directory looks like. This is especially true in CI where I can't just look at the directories on disk.
This changes `makeSyncScenario` to return `expectDirs` which is an assertion all the directories. This allows us to generate a snapshot an all the directories at once, and more importantly, see what all the directories look like when a snapshot fails.

Use expectDirs instead

---

spec/__support__/edit-graphql.ts
spec/__support__/filesync.ts
spec/commands/deploy.spec.ts
spec/commands/sync.spec.ts
src/services/app/edit-graphql.ts

This adds a `PQueue` inside `EditGraphQL` subscriptions so that we:
1. Process messages in the order we receive them
2. Never process messages in parallel
This allows our GraphQL subscription handlers to be async while still ensuring they run in the expected order. This also helps us write tests where we can `await` the handler of a message rather than watching for external state to change.
None of our current subscriptions need to process messages in parallel, in fact filesync already uses a `PQueue` internal to prevent this from happening. If we ever need to process messages in parallel in the future, we can add a `concurrency` option.

Use PQueue inside EditGraphQL subscriptions

---

.changeset/weak-pumas-talk.md
spec/commands/deploy.spec.ts
src/commands/deploy.ts

Ggt `deploy` currently will get stuck if the deploy is interrupted and no more progress updates are sent. We need to handle the case where the websocket connection closes due to a step in the deploy erroring and let the user which step it failed at and exit so they aren't stuck waiting for progress updates.

Handle early exit due to deploy progress interruption

---

spec/__support__/edit-graphql.ts
spec/__support__/filesync.ts
spec/vitest.setup.ts

Removes a race condition that causes the process to exit. I ran into this a lot when running all the tests at once locally.
It was caused by mocking the initial result of a GraphQL subscription. The initial result was resolved out of band and would sometimes cause `Unexpected local files version` during the `writes all received files before stopping` test.
Mocking the initial result of a GraphQL subscription feels like an anti-pattern, and we don't need to do it anymore, so I removed it.

Fix process exit flake

---

.changeset/some-weird-name.md
spec/services/filesync/hashes.spec.ts
src/services/filesync/conflicts.ts
src/services/filesync/hashes.ts

Simon ran into the `TooManySyncAttemptsError`: https://discord.com/channels/836317518595096598/1169734587899977870/threads/1186047502525399160
```
09:43:15 TRACE hashes: hashes are not equal
path: '.gadget/'
aHash:
sha1: '291c523421f3b1068eab749a5fcba60fc772e159'
permissions: 509
bHash:
sha1: '291c523421f3b1068eab749a5fcba60fc772e159'
permissions: 493
09:43:15 TRACE hashes: file updated
path: 'lib/'
sourceHash:
sha1: '9d062bafff17ba8b9a1215c4c51485134d509d91'
permissions: 493
targetHash:
sha1: '9d062bafff17ba8b9a1215c4c51485134d509d91'
permissions: 509
09:43:15 TRACE hashes: file updated
path: 'delivery/'
sourceHash:
sha1: '391cb1e07c5f1f4e3000e0fd125802c7a9b1dc96'
permissions: 493
targetHash:
sha1: '391cb1e07c5f1f4e3000e0fd125802c7a9b1dc96'
permissions: 509
09:43:15 TRACE hashes: file …
```

Ignore directory permissions

---

.changeset/gentle-cougars-help.md
README.md
scripts/generate-readme.ts
spec/commands/__snapshots__/root.spec.ts.snap
spec/services/filesync/directory.spec.ts
src/commands/login.ts
src/commands/logout.ts
src/commands/version.ts
src/commands/whoami.ts
src/services/filesync/directory.ts

Another user ran into the `TooManySyncAttemptsError`:
https://discord.com/channels/836317518595096598/1186331446516908164
This is happening because we don't include `yarn-error.log` in hashes gadget side, so ggt keeps thinking it doesn't exist and wants to create it.
This PR ignores `yarn-error.log` ggt side as well so this doesn't happen anymore.

Ignore yarn-error.log from hashes

---

src/commands/deploy.ts
src/services/filesync/filesync.ts

Just some refactoring to make the #1072 PR smaller
- Renames `_getHashes` -> `hashes`
- Adds `FileSyncHashes` which is what `hashes` returns
- Adds `inSync` to `FileSyncHashes`
- Uses `inSync` inside deploy command
- Splits `sync` into 2 methods:
- An outer public method that returns when we're in sync
- An inner private method that performs the steps to get in sync
- This avoids potential stack overflow exceptions which is more likely to happen during a re-sync that #1072 adds

Refactoring before "Files version mismatch" fix

---

npm-shrinkwrap.json

Hey!! 👋
Was just updating my NUR repo and realized I should share a patch that makes it possible to build ggt with `buildNpmPackage`: https://gitlab.com/kira-bruneau/nur-packages/-/commit/1f044bbc14bb84acd51533dfadc8b63e7376c54d.
Apparently `npm install` doesn't include the integrity & resolved fields for packages that were already in the cache? https://github.com/npm/cli/issues/4263.
I added those fields back with:
```shell
nix run github:jeslie0/npm-lockfile-fix ./npm-shrinkwrap.json && npm install
```

Add missing resolved & integrity fields in npm-shrinkwrap.json

---

.changeset/disable-permission-syncing.md
spec/services/filesync/hashes.spec.ts
src/services/filesync/hashes.ts

A number of users are running into `TooManySyncAttemptsError` because file permissions aren't being updated on Gadget and/or the local filesystem.
I thought the issue was only related to directory permissions, which is what #1075 was supposed to fix, but [Simon proved that a file's permissions aren't being updated either](https://discord.com/channels/836317518595096598/1186047502525399160).

Disable file permission syncing

---

spec/__support__/context.ts
spec/__support__/filesync.ts
spec/commands/sync.spec.ts
spec/services/filesync/filesync.spec.ts
spec/types.ts
src/commands/deploy.ts
src/commands/root.ts
src/commands/sync.ts
src/services/command/context.ts
src/services/filesync/filesync.ts
src/services/util/types.ts

In order to implement #1072, I'm going to need access to the current `Context` inside the `FileSync` class, so this PR propagates the context down to it.
This also cleans up the `Context` class, adds docs, and makes deploy use the `Context`'s logger instead of `FileSync`'s.

Propagate context

---

spec/__support__/filesync.ts
spec/services/filesync/filesync.spec.ts
src/services/filesync/filesync.ts
src/services/util/is.ts

Some more changes before #1072:
- Ensure `publishFileSyncEvents` doesn't retry "Files version mismatch" errors
- Add `TooManySyncAttemptsError` tests

Pre "Files version mismatch" fix

---

.changeset/retry-more.md
src/services/http/http.ts

I noticed ggt was crashing due to `EADDRNOTAVAIL` and `EHOSTUNREACH` errors while sending http requests. This PR makes those error codes retryable and increases the amount of retry attempts for all http requests.

Retry more

---

.changeset/use-primary-domain.md
src/commands/sync.ts

We need to use the primary domain for the edit and playground links when an app has a custom domain. This is inline with how Gadget proper works.

Display primary domain

---

.changeset/retry-backup-more.md
src/services/filesync/filesync.ts

I'm still seeing ggt crash with `dest already exists` while moving files to `.gadget/backup/`. This crash seems to only be happening on Windows, so this increases how many times we attempt to backup files on Windows.

Increase file backup attempts on Windows

---

spec/commands/deploy.spec.ts
src/__generated__/edit.graphql
src/__generated__/graphql.ts
src/commands/deploy.ts
src/services/app/edit/operation.ts

Updates to ggt deploy:
- Previously, if a deploy errored over on Gadget server-side, `ggt deploy` would hang indefinitely. This was handled previously by throwing an error inside the `publishStatus` subscription's async iterator to close and signal to the client that the connection was closed. GGT would then receive this signal that the websocket was closed unexpectedly and know to exit.
- Unfortunately though all errors thrown from inside the subscription `next()` iterator are parsed as just `CloseEvent` errors (Internal Error) by the graphql-ws client, there's no way to pass any custom error messages or data (can't find any documentation on this but I've experimented with this a bunch). This data is pretty useful and we want to receive it, as well as some other data like the traceId of …

Better ggt deploy publish contract error handling and completion

---

.changeset/purple-turtles-design.md
.changeset/show-fatal-errors.md
spec/__support__/filesync.ts
spec/services/filesync/filesync.spec.ts
src/__generated__/edit.graphql
src/__generated__/graphql.ts
src/services/app/edit/operation.ts
src/services/filesync/filesync.ts

In an upcoming Gadget feature, we will introduce a new error level called `Fatal` that comes from the files and will make the app unable to run.
This PR is to print out these file-related fatal errors during the `ggt sync` mode to inform the user of issues with the files.
Gadget side for the new GraphQL response value:
https://github.com/gadget-inc/gadget/pull/9652

Print out file-related fatal errors on `ggt sync`

---

.changeset/files-version-mismatch-fix.md
src/services/filesync/filesync.ts

We shipped a newer files version mismatch error server side that isn't being handled anymore. This makes ggt handle the new error.

Handle GGT_FILES_VERSION_MISMATCH

---

.changeset/improve-usage.md
scripts/generate-readme.ts
spec/commands/__snapshots__/root.spec.ts.snap
spec/commands/root.spec.ts
spec/services/command/command.spec.ts
src/commands/deploy.ts
src/commands/list.ts
src/commands/login.ts
src/commands/logout.ts
src/commands/root.ts
src/commands/sync.ts
src/commands/version.ts
src/commands/whoami.ts
src/services/command/command.ts

This PR:
- Makes our ggt commands able to differentiate between `-h` and `--help`
- Makes the `sync` and `deploy` commands print more detailed information if `--help` is passed
- Updates the `deploy` help text
- Most of these changes are personal preference, so if you don't like them let me know and I'll revert!
To make this PR easier to read, here's the **before** and **after** for the `sync` and `deploy` help texts.
`ggt sync --help`
<details>
<summary>Before</summary>
```
Sync your Gadget environment's source code with your local filesystem.
USAGE
ggt sync [DIRECTORY]
ARGUMENTS
DIRECTORY                  The directory to sync files to (default: ".")
FLAGS
-a, --app=<name>           The Gadget application to sync files to
--prefer=<filesystem>  Prefer "local" or "gadget" conflicting …
```

Improve Usage

---

spec/__support__/app.ts
spec/__support__/filesync.ts
spec/commands/list.spec.ts
spec/commands/sync.spec.ts
spec/services/app/arg.spec.ts
spec/services/app/edit.spec.ts
spec/services/filesync/filesync.spec.ts
src/commands/sync.ts
src/services/app/app.ts
src/services/app/edit/client.ts
src/services/command/context.ts
src/services/filesync/filesync.ts
tsconfig.json

Adds support to ggt for synching to and from multi environments app.
- New `--environment` / `-e` flag for selecting which environment to sync to
- New environment selector for when mutl-environment is enabled on the app you're synching from/to
- I've removed most of the references to `mtime`
- I wanted to possibly update `makeSyncContext` to support multi-environment but I think it'll be worth shipping this quick and coming back around to do it later. In the meantime I've tried adding tests around the edges for this PR.
A new sync command might look like this: `ggt sync --app my-app --environment cool-new-development`
🎩 instructions:
I think there's a bunch of states that should be tophatted:
1. non multi-environment app
2. multi-environment app
3. "legacy" app where split environment is …

add multi environment support

---

.changeset/disallow-deploy-with-fatal-errors.md
spec/commands/deploy.spec.ts
src/commands/deploy.ts
src/services/filesync/error.ts
src/services/filesync/filesync.ts
src/services/util/problems-group.ts

This PR disallows app deployment on `ggt deploy` if fatal errors exist in their app, then show the errors and exits `ggt` early.
Since fatal errors will not make the app operational, we should not allow an app with fatal errors to deploy and break its production app.
Gadget side:
https://github.com/gadget-inc/gadget/pull/9657

Disallow deploy on `ggt deploy` if there are fatal errors

---

spec/commands/__snapshots__/root.spec.ts.snap
spec/commands/deploy.spec.ts
src/commands/deploy.ts

- added info/help text about using the `--environment` flag alongside deploy command
- updated status text to show proper environment
- updated deploying text to show which environment you're deploying from
There's a bug with the `status.output` not sending back the correct environment logs, that'll be fixed in a separate PR.
For multi-environment deploy to work properly you'll have to wait for https://github.com/gadget-inc/gadget/pull/9956 to be in main.

small QOL changes for ggt deploy multi-environment

---

flake.nix
spec/__support__/mock.ts
spec/commands/__snapshots__/root.spec.ts.snap
spec/commands/__snapshots__/status.spec.ts.snap
spec/commands/status.spec.ts
spec/services/filesync/sync-json.spec.ts
src/commands/deploy.ts
src/commands/dev.ts
src/commands/pull.ts
src/commands/push.ts
src/commands/status.ts
src/services/filesync/changes.ts
src/services/filesync/filesync.ts
src/services/filesync/sync-json.ts
src/services/output/log/logger.ts
src/services/output/log/printer.ts
src/services/output/sprint.ts

This improves the output of "ggt status" and a few other scenarios.
The biggest change in here is the ability to buffer `println` calls. This makes it easier to format a large message by using multiple `print` calls, and still have the entire message logged as a single statement. This isn't very useful today, but will be in the future when we allow callers to specify what should be printed when `--json` is passed vs when it's not.

Improve "ggt status" output

---

.changeset/.show-fatal-errors.md
.changeset/disallow-deploy-with-fatal-errors.md
.changeset/improve-usage.md
README.md
spec/commands/root.spec.ts
src/commands/root.ts
src/services/command/command.ts

- Add `ggt open` to root usage
- Remove `--json` from usage
- The code is there to support it, but the implementation is currently half baked
- Remove fatal-error change logs
- Not relevant to users yet

Last minute fixups

---

.changeset/handle-file-backups.md
spec/services/filesync/filesync.spec.ts
src/services/filesync/filesync.ts
src/services/util/is.ts

We've seen errors like this for a while now.
```
Error: ENOTDIR: not a directory, lstat '.gadget/backup/routes/webhooks/POST-github.js'
```
I could never figure out what caused this because I made ggt `rm -rf` the existing backup file (if it exists) in #926.
---
However, I **finally** figured out the scenario that causes this issue:
1. Have `ggt dev` running in the background
2. Create a file in the editor that looks like a directory, e.g. `routes/webhooks`
3. Delete the file in the editor, causing ggt to move it to `.gadget/backup/routes/webhooks`
4. Create a nested file in the editor, e.g. `routes/webhooks/POST-github.js`
5. Delete the nested file in the editor, causing ggt to move it to `.gadget/backup/routes/webhooks/POST-github.js`
The issue happens here because …

Handle file backups

---

spec/commands/__snapshots__/root.spec.ts.snap
spec/commands/root.spec.ts
src/commands/deploy.ts
src/commands/dev.ts
src/commands/list.ts
src/commands/login.ts
src/commands/logout.ts
src/commands/open.ts
src/commands/pull.ts
src/commands/push.ts
src/commands/root.ts
src/commands/status.ts
src/commands/version.ts
src/commands/whoami.ts

@mdamy made a really great CLI design doc: https://docs.google.com/document/d/1nNL12-9y_wdf4ANWDC1kvWOymkMM9B-4CWfuad3_tHo/edit
To better standardize ggt I've gone a head and copied most of the usages from it. Another decision was to remove the less verbose usage/help when using `-h` now it'll always be the same help regardless.

update usages to match new CLI design system

---

.changeset/log-login-url.md
src/commands/login.ts

If `open` fails to open the user's browser, but doesn't throw an error, then user's can't log manually log in themselves.
This logs the login URL so users can manually click the link.

Add browser opening log statement in login command

---

src/ggt.ts
src/services/output/log/structured.ts
src/services/output/report.ts
src/services/output/sentry.ts

`@sentry/node` is big and we only need to load  when `--telemetry` is enabled.

Lazy load Sentry

---

.changeset/fix-ggt-deploy-hanging.md
src/commands/deploy.ts

I was able to semi-reproduce the "ggt deploy hanging" issue by running `ggt deploy --allow-problems` while `ggt dev` was running at the same time.
Why did `ggt dev` have to be running and why did I have to pass `--allow-problems`? I have no idea, but after disposing the client like Harry suggested I wasn't able to reproduce the issue anymore 🎉

Dispose client after deploying

---

.changeset/fix-ggt-deploy-confirm.md
src/commands/deploy.ts
src/services/app/client.ts

To fix the `ggt deploy` hanging issue in #1576, we started disposing of the `graphql-ws` client using the `onComplete` callback. While this resolved the hang, it caused another problem: after confirming a user wants to proceed with deployment, `ggt deploy` would immediately exit.
This is because after a user confirms they want to continue, `ggt deploy` unsubscribes and re-subscribes with different arguments. The unsubscribe was disposing of the `graphql-ws` client, so the subsequent re-subscribe would no-op, causing `ggt` to exit.
Rather than disposing the client, this PR changes `ggt deploy` to unsubscribe in the `onComplete` callback. This solved both issues because:
1. We're not calling dispose on the client anymore so re-subscribing will always work
2. I realized that we were …

Unsubscribe rather than disposing

---

src/services/app/client.ts

This **actually** fixes the "ggt deploy immediately exiting" bug that I thought I fixed in #1581...
Calling unsubscribing within the onComplete callback causes ggt to unsubscribe from the resubscription after confirming, causing ggt to immediately exit 🤦
This fixes that by clearing the queue of callbacks after unsubscribing the first time.

Clear callback queue when caller unsubscribes

---

.changeset/drop-v04-support.md
spec/__support__/filesync.ts
spec/commands/dev.spec.ts
spec/commands/pull.spec.ts
spec/commands/push.spec.ts
spec/services/filesync/filesync.spec.ts
spec/services/filesync/sync-json.spec.ts
src/services/filesync/sync-json.ts

We changed the structure of `.gadget/sync.json` when we shipped ggt v1 to support multiple environments. However, we still stored the old structure within the new structure in case users had to downgrade or had multiple versions of ggt installed.
**Before**
```json
{
"app": "some-app",
"filesVersion": "456",
"mtime": 1711134057476
}
```
**After**
```json5
{
// new structure that v1 uses
"application": "some-app",
"environment": "development",
"environments": {
"development": {
"filesVersion": "456"
}
},
// old structure that v0.4 uses
"app": "some-app",
"filesVersion": "456",
"mtime": 1711134057476
}
```
Now that ggt v1 has been out for 6 months now, let's stop saving the old structure within `.gadget/sync.json` so we can clean up old code that shouldn't be used anymore.
I didn't remove …

Drop support for ggt v0.4

---

.changeset/add-data-deleted-warning-on-deploy.md
spec/commands/__snapshots__/root.spec.ts.snap
spec/commands/deploy.spec.ts
src/__generated__/edit.graphql
src/__generated__/graphql.ts
src/commands/deploy.ts
src/services/app/edit/operation.ts
src/services/filesync/changes.ts
src/services/output/confirm.ts

Implements the GGT side of https://linear.app/gadget-dev/issue/GGT-6590/hard-deleting-models-or-fields-needs-to-warn-on-deploy
Adds a new `--allow-data-delete` flag to the deploy command to force/acknowledge deploys deleting data as a result of modifying fields/removing models.

implements ggt side of data delete warning

---

.changeset/fix-empty-string-assertion-error.md
src/services/output/log/format/pretty.ts

When we format the value of a log field, we split the value by new line, early return if the number of lines is 0, and assert the first line isn't null to make typescript happy:
```ts
const formatValue = (value: string, color: (s: string) => string, indent: number): string => {
if (!value) {
return EMPTY;
}
const lines = value.split(NEW_LINE);
if (lines.length === 0) {
return EMPTY;
}
const buf: string[] = [];
const firstLine = lines.shift();
assert(firstLine); // can't be null/undefined because we early return if lines.length === 0 above, but typescript doesn't know that so we assert here
buf.push(color(firstLine));
// ...
}
```
The issue with this is that `assert(firstLine)` will throw if `firstLine` is an empty string because an empty string is a falsy value 🤦‍♂️. This can be …

Fix log line assertion error

---

.changeset/dest-already-exists.md
src/services/filesync/filesync.ts

This is an attempt to fix the `Error: dest already exists.` issues that keep popping up.
- https://github.com/gadget-inc/ggt/issues/1819
- https://github.com/gadget-inc/ggt/issues/1851
- https://github.com/gadget-inc/ggt/issues/1853
While trying to reproduce this issue, I noticed the `Error: dest already exists.` error being logged when I deleted a model in Gadget's editor and then ran `ggt pull`. The error was happening while attempting to move deleted files into `.gadget/backup/`. The deleted files that failed to move into `.gadget/backup/` eventually succeeded because we wrap the move within a `pRetry`, so I didn't experience the final failure that causes ggt to crash.
I'm not sure how the file moves eventually succeeded because I didn't see the `"removing file in the way of backup …

Backup one file at a time

---

.changeset/ggt-pull-production.md
spec/commands/__snapshots__/root.spec.ts.snap
spec/commands/pull.spec.ts
spec/services/filesync/__snapshots__/sync-json.spec.ts.snap
spec/services/filesync/sync-json.spec.ts
src/commands/pull.ts
src/commands/push.ts
src/services/app/client.ts
src/services/filesync/sync-json.ts

This PR allows users to `ggt pull --from=production`.
When users run `ggt pull --env=<some-env>` today, their `.gadget/sync.json` updates to the specified environment, causing all future commands to happen on that environment. This doesn't make sense for the production environment though, because the only command that can be run against the production environment is `ggt pull`, so this PR makes ggt **not** update the `.gadget/sync.json` to the production environment when `ggt pull --from=production` is ran.

Allow `ggt pull --from=production`

---

.changeset/enable-source-maps.md
package.json
src/main.ts

It's very difficult to figure out where an error was thrown when the stack trace looks like this:
```
Error: dest already exists.
at Gm (dist/chunk-GIAIN3IJ.js:7:2753)
at async tt.retries (dist/chunk-IPKFNVOS.js:175:708)
at async I._fn (dist/chunk-IPKFNVOS.js:169:5410)
```
We're already outputting source maps, but we weren't telling node to use them 🤦.
This PR fixes that by passing `--enable-source-maps` to node when running ggt, which makes the line numbers point to the original `.ts` file. This PR also adds `--keep-names` to esbuild so that the function names in the stack trace are also correct.

Use --enable-source-maps and --keep-names

---

.changeset/gold-bikes-dance.md
spec/ggt.spec.ts
src/ggt.ts

This PR introduces a check to make sure users are not running `ggt` in terminal environments that are not supported, for example, places that can run a terminal command in the Gadget editor.

Do not proceed if ggt runs in unsupported terminal environments

---

.changeset/tall-crabs-enjoy.md
src/services/http/http.ts

Self explanatory. SSLv3 is obsolete, deprecated, and it looks like there are some bugged versions of OpenSSL floating around that can cause ggt to throw errors. While that is a fairly rare problem and OpenSSL updates are the real solution, we don't control client OpenSSL patching, and there's just not really any advantage to keeping SSLv3 support.

Specify that https agents must use at least TLSv1.1

---

.changeset/beige-apples-greet.md
spec/commands/root.spec.ts
src/commands/root.ts
src/services/app/edit/edit.ts
src/services/app/error.ts
src/services/http/http.ts
src/services/output/log/format/json.ts
src/services/util/is.ts

Now that we prompt for default options including sending telemetry and crash data as our recomended default, we have been able to trace some issues. First, when authentication expires after a command is already running it comes through it a format we weren't accounting for which resulted in ggt crashing instead of a clean exit with a prompt to sign in again. Another instance, it is possible for the json output setup to encounter an undefined which it would not convert to an empty string as with regular text, and it would instead crash.
Assorted fixes for some issues that were seen via app telemetry/crash reporting

Misc fixes from telemetry
